# -*- coding: utf-8 -*-
"""app_healthaitrial.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Yi53soPPxpa8hXX_nGK6YAnAdHxxeE8Q

# CUSTOM HEALTH REPORT with REMEDY RECOMMENDATION
# Streamlit APP

## Importing Libraries
"""

# '/home/adminuser/venv/bin/python -m pip install --upgrade pip'

# pip install --upgrade pip

# pip install streamlit

import numpy as np
import pandas as pd
import streamlit as st
from healthabnormalcheck import check_abnormal_values
# from medsemichatbot import chatbot_logic_loop

# Check Health Input Data

# Input Health Data

def input_health_data():

  with st.form(key='my_form'):
    age = st.slider("Enter Age:", min_value=3, max_value=110, step=1)
    weight = st.slider("Enter Weight (kg):", min_value=5.0, max_value=110.0, step=0.1)
    height = st.slider("Enter Height (cm):", min_value=50.0, max_value=190.0, step=0.1)
    hemoglobin = st.number_input("Enter Hemoglobin value (g/dL): ", step=0.1)
    platelets = st.number_input("Enter Platelet count (mcL):", step=1)
    HDL = st.number_input("Enter HDL Cholesterol (mg/L): ", step=1)
    LDL = st.number_input("Enter LDL Cholesterol (mg/L): ", step=1)
    sugar = st.number_input("Enter Glucose / Fasting Blood Sugar (mg/dL): ", step=1)

    # Add a "Form Submit" button for batch inputs
    submit_button = st.form_submit_button(label='Submit')

    if submit_button:
      return age, weight, height, hemoglobin, platelets, HDL, LDL, sugar
      # st.write(age, weight, height, hemoglobin, platelets, HDL, LDL, sugar)

  # If the button is not clicked
    # return age, weight, height, hemoglobin, platelets, HDL, LDL, sugar

# Testing in .ipnyb

# transfer_data = input_health_data()
# age, weight, height, hemoglobin, platelets, HDL, LDL, sugar = transfer_data

# print(f"age {age}", f"weight {weight}", f"ht {height}")

def app_healthai():
    st.title("WELCOME TO HEALTH AI")

    # Ask the user for the input method (Custom or Chat)
    # input_method = st.radio("Choose Input Method:", ["Custom Health Report", "Chat Assistant"])
    #input_method = st.button("Customized Health Report")
    #chat_method = st.button("Chatbot Assistant")

    
    st.title("Customized Health Report")

    # User input data
    transfer_data = input_health_data()
    age, weight, height, hemoglobin, platelets, HDL, LDL, sugar = transfer_data

     
    if all(value is not None for value in (age, weight, height, hemoglobin, platelets, HDL, LDL, sugar)):
       # Checking for abnormal values
       result1, result2 = check_abnormal_values(age, weight, height, hemoglobin, platelets, HDL, LDL, sugar)

       # Display Results
       st.write("")
       if result1:
         st.warning("<<<<< Abnormalities in Health Report >>>>>")
         st.write("Note: Consult your Doctor for detailed Investigation")
         st.write("")

       for item in result1:
         st.write("-", item)

       if result2:
         st.write("")
         st.write("")
         st.write("<<<<< Normal Values >>>>>")
         st.write("Good Job! Stay Healthy!")
         st.write("")
       for item in result2:
         st.write("-", item)

       if not result1 and not result2:
         st.success("All values are within normal ranges. Stay Healthy!")

      # else:
        # st.warning("Please fill all the values before submission")


    #elif chat_method:
      #st.title("Chatbot Assistant")


if __name__ == "__main__":
  app_healthai()
