# -*- coding: utf-8 -*-
"""healthabnormalcheck.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Rnc9wvN1-ToNipvDxhDHcLOxcRSbcuI1

# HEALTH REPORT with REMEDY RECOMMENDATION

## Importing Libraries
"""

import json
import numpy as np
import pandas as pd

"""# Check Health Input Data"""

def check_abnormal_values(age, weight, height, hemoglobin, platelets, HDL, LDL, sugar):
    output1 = []
    output2 = []

    # Age
    if not (4 <= age <= 110):
        output1.append("Age out of normal range.")

    # Weight
    if not (10 <= weight <= 100):
        output1.append("Weight out of normal range.")

    # Height
    if not (50 <= height <= 190):
        output1.append("Weight out of normal range.")

    # BMI
    bmi= weight/(height/100)**2
    if bmi<18.5:
      output1.append(f"Your Body Mass Index (BMI) is {bmi:.2f}. You are Underweight and possibly malnutritioned.")
      output1.append("Health risks associated with being underweight: Vitamin deficiencies, Anemia, Low Immunity, Hormonal Imbalances, Osteoporosis, etc")
      output1.append("")
    elif bmi>=18.5 and bmi<25:
      output2.append(f"Your Body Mass Index (BMI) is {bmi:.2f}. Healthy BMI range is between 18.5 to 25. You have a Healthy weight range.")
    elif bmi>=25 and bmi<30:
      output1.append(f"Your Body Mass Index (BMI) is {bmi:.2f}. You are Overweight! Healthy BMI range is between 18.5 to 25.")
      output1.append("You are at risk to develop serious health problems.")
      output1.append("Health risks associated with being Overweight: Diabetes, Heart Stroke, Cataract, Breathing problems, Cancer, etc")
      output1.append("")
    else:
      output1.append(f"Your Body Mass Index (BMI) is {bmi:.2f}. You are Obese! Healthy BMI range is between 18.5 to 25.")
      output1.append("You are at serious risk to develop serious health problems.")

    # Hemoglobin
    if not (13 <= hemoglobin <= 17):
        if hemoglobin < 13:
          output1.append("Low Hemoglobin & out of Normal range of 13 to 17 g/dL")
          output1.append("Improve Diet with iron-rich foods like Legumes, Green vegetables, nuts, Fruits such as Pomegranate, Amla, Apples.")
          output1.append("")
        elif hemoglobin > 17:
          output1.append("Abnormal High Hemoglobin & out of Normal range of 13 to 17 g/dL")
          output1.append("Symptoms for High Heoglobin include Fatigue, Dizziness, excessive Sweating, etc")
          output1.append("It is recommended to Consult your Doctor.")
          output1.append("")
    else:
       output2.append("Your Hemoglobin values are within the Normal range of 13 to 17 g/dL.")

    # Platelets
    if not (135000 <= platelets <= 450000):
        if platelets < 135000:
            output1.append("LOW Platelet count & out of Normal range of 135,000 to 450,000 mcL")
            output1.append("This may be due to Bacterial / Viral infections, Chemotherapy, Autoimmune diseases.")
            output1.append("Improve Low platelet count naturally with foods like Pomgrenate, Pumpkin, Papaya & citrous fruits; Avoid alcohol!")
            output1.append("")
        elif platelets > 450000:
            output1.append("ABNORMAL HIGH Platelet count & out of Normal range of 135,000 to 450,000 mcL")
            output1.append("This may be due to prolonged bleeding or blood loss, Anemia from low iron levels, Infection & Inflammation.")
            output1.append("Cinnamon contains a compound called “cinnamaldehyde” which is known to reduce platelet aggregation.")
            output1.append("")
    else:
       output2.append("Your Platelets count are within the Normal range of 135,000 to 450,000 mcL")


    # HDL Cholesterol
    if not (HDL >= 60):
        output1.append("Optimum HDL Cholesterol is essential for removing harmful substances from your blood & helps your Liver function.")
        output1.append("Your HDL Cholesterol is LOW & potential risk for Heart disease.")
    else:
      output2.append("HDL Cholesterol is optimal for your Heart health.")

    # LDL Cholesterol
    if not (LDL <= 100):
        output1.append("High LDL Cholesterol can cause plaque to develop in your arteries.")
        output1.append("Your LDL Cholesterol is HIGH & potential risk for Heart disease.")
    else:
      output2.append("LDL Cholesterol is optimal for your Heart health.")

    # Sugar
    if not (70 <= sugar <= 100):
        if sugar < 70:
            output1.append("Your fasting Blood Sugar is LOW & out of Normal range of 70 to 100 mg/dL")
            output1.append("Low Blood Glucose levels are common with people with Type 1 or Type 2 Diabetes who take their medications.")
            output1.append("This can also be due to Kidney or Liver disease.")
            output1.append("Symptoms for Low Blood Sugar include Fatigue, Hunger, Headache, Fast Heartbeat, Fainting, etc")
            output1.append("Carry something with you that will raise your blood sugar quickly, such as sugary drinks, sweets or glucose tablets.")
            output1.append("")
        elif sugar > 100:
            output1.append("Your fasting Blood Sugar is at ABNORMAL HIGH level & out of Normal range of 70 to 100 mg/dL")
            output1.append("High Blood Glucose levels can be sign of Diabetes or HyperThyroidism.")
            output1.append("Symptoms include increased thirst and urination, Blurred Vision, Eye Pain, Fatigue, Weight Loss,")
            output1.append("Numbness in Hands or Feet, Rapid or irregular heartbeat, Insomnia, etc")
            output1.append("Home remedies for High Blood Sugar are Excercising regularly, manage your carb intake, Eat more Fiber & foods with low GI index.")
            output1.append("Get good Sleep, avoid Sedentary Lifestyle and reduce Stress.")
            output1.append("However, in severe cases, you should go to the hospital.")
            output1.append("")
    else:
       output2.append("Your fasting Blood Sugar / Glucose is within the Normal range of 70 to 100 mg/dL")


    return output1, output2

# Input Health Data

# def input_health_data ():
#   age = int(input("Enter Age: "))
#   weight = float(input("Enter Weight (Kg): "))
#   height = float(input("Enter Height (cm): "))
#   hemoglobin = float(input("Enter Hemoglobin value (g/dL): "))
#   platelets = int(input("Enter Platelet count (mcL): "))
#   HDL = float(input("Enter HDL Cholesterol value (mg/L): "))
#   LDL = float(input("Enter LDL Cholesterol value (mg/L): "))
#   sugar = float(input("Enter Glucose / Fasting Blood Sugar value (mg/dL): "))

#   return age, weight, height, hemoglobin, platelets, HDL, LDL, sugar

# age, weight, height, hemoglobin, platelets, HDL, LDL, sugar = input_health_data()

# Checking for abnormal values
# result1, result2 = check_abnormal_values(age, weight, height, hemoglobin, platelets, HDL, LDL, sugar)

# Displaying the result
# Customized Instant Report

# print("Customized Health Report")
# print("")
# if result1:
#     print("<<<<< Abnormalities in Health Report >>>>>> ")
#     print("Note: Consult your Doctor for detailed Investigation")
#     print("")
#     for item in result1:
#         print("-", item)

# if result2:
#     print("")
#     print("")
#     print("<<<<< Normal Values >>>>>")
#     print("Good Job! Stay Healthy!")
#     print("")
#     for item in result2:
#         print("-", item)

# if not result1 and not result2:
#     print("All values are within normal ranges. Stay Healthy!")